```mermaid
flowchart TD
    A((Start)) --> B[Start]
    B --> C[Wear Safety Gear]
    C --> D[Strip Wires]
    D --> E{Heat Shrink Tubing?}
    E --> F{Slide Heat Shrink Tubing}
    F --> G[Align and Weave Wires]
    G --> H[Twist Wires]
    H --> I[Position Splice]
    I --> J[Solder - First Side]
    J --> K[Solder - Second Side]
    K --> L[Completed Inline Splice]
    L --> M[Cool Splice]
    M --> N{Insulation Required?}
    N --> O{Heat Shrink Used?}
    O --> P[Heat Tubing to Seal]
    O --> Q[Wrap with Electrical Tape]
    P --> Z((End))
    Q --> Z
    B{Gather Materials} --> C
    F{No} --> H
    F{Yes} --> G
    H{Yes} --> I
    H{No} --> J
    K{Yes} --> L
    K{No} --> M
    M{Yes} --> N
    M{No} --> O
    N{Yes} --> P
    N{No} --> Q
    Z{End}
```