```mermaid
flowchart TD
    A((Start)) --> B[Cut three rectangles from cardboard]
    B --> C{Draw outline of body, wings, stabilizer}
    C --> D[Cut the drawn parts ou]
    D --> E{Create connections for assembly}
    E --> F[Bend main wing]
    F --> G[Tape coin at nose]
    G --> H{Cut hook for rubber band launch?}
    H --> I[Cut hook on the bottom]
    I --> J{Decorate the glide}
    J --> K[Take glider outside to fly]
    K --> L[Full assembled and decorated glider]
    L --> M{Enjoyed the instructable?}
    M --> N[Vote for instructable]
    N --> P((End))
    P --> ((Start))
    P --> ((End))
```