```mermaid
flowchart TD
    A((Start)) --> B[Obtain Music]
    B --> C[Study Music]
    C --> D{Better Understanding of Music}
    D --> E[Identify Phrases in Music]
    E --> F{Learn from End}
    F --> G[Learn from End]
    G --> H[Read Off the Music]
    H --> I[Learn Music from End]
    I --> J{Divide Music into Chunks}
    J --> K[Memorize first Chunk with Eyes Open]
    K --> L[First Chunk Memorized?]
    L --> M[Move to Next Chunk]
    M --> N{Correct Mistakes}
    N --> O[Alternate Eyes Closed and Eyes Open]
    O --> P((End - Music Memorized))
    P --> Q[Secure Memory of Piece]
    Q --> R{Check and Correct Wrong Notes}
    R --> S[Memorize Next Chunk]
    S --> T{New Chunk Memorized?}
    T --> U[Continue with Next Chunk]
    U --> V{Play from Beginning to Memorized Point}
    V --> W{Play from Memory 5x?}
    W --> X{Continue to Next Chunk}
    X --> Y{Sing or Hum Music}
    Y --> Z[Received Feedback and Continue with Next Chunk]
    Z --> ((End))
    L --> ((End))
```