```mermaid
flowchart TD
    A((Start)) --> B[Identify construction materials and methods]
    B --> C[Construct walls]
    C --> D{Solid masonry?}
    D --> E[Use reinforced concrete = 4 inches thick]
    D --> F[Hollow masonry = 12 inches?]
    F --> G{Hollow masonry 8-12 inches with fire-resistance rating?}
    G --> H{Assembly with fire-resistance rating?}
    H --> I{Use hollow masonry = 12 inches thick]
    I --> J[Ensure 2-hour fire-resistance rating]
    J --> K[Ensure assembly has a 2-hour fire-resistance rating]
    K --> L[Review wall specifications]
    L --> M{Concrete floors and roof?}
    M --> N[Reinforced concrete floors & roof?]
    N --> O[Use reinforced concrete = 4 inches thick]
    O --> P{Use protected metal supports with 2-hour fire-resistance rating]
    P --> Q[Install structural metal supports]
    Q --> R[Use pre-approved concrete units]
    R --> S{Review floor and roof specifications]
    S --> T[Utilize pre-approved concrete units]
    T --> U[Pull cables right before pouring concrete]
    U --> V[Release cables as concrete cures]
    V --> W[Utilize post-tensioned concrete units]
    W --> X[Pull one end of cable right after pouring concrete]
    X --> Y[Completed structure meeting SD Class & BC Type IIA requirements]
    Y --> ((End))
```