```mermaid
flowchart TD
    A((Start)) --> B[Gather all materials and ingredients]
    B --> C[Measure out 2 cups of warm water]
    C --> D[Calculate required amount of gelatin]
    D --> E[Slowly mix in the 4 packets of gelatin]
    E --> {Does gel look as expected?}
    {Does gel look as expected?} --> F[Freeze mixture for 30 minutes]
    F --> G[Pour mixture into Tupperware]
    G --> H[Let sit at room temperature for 10 minutes]
    H --> I[Refrigerate for 30 minute:]
    I --> J[Freeze again for 12-14 hours]
    J --> K[Check if gel is solid and properly formed]
    K --> L[Does gel as expected?]
    L --> M[Ballistics gel is ready for use]
    M --> N[(End)]
```